# 使用轻量级Alpine基础锐像
FROM ccr.ccs.tencentyun.com/yubang/alpine:3.6
# 安装依赖项
RUN apk add --no-cache curl tar wget netcat-openbsd
#下载File Browser（指定最新版本）
RUN wget https://github.com/bhzhangsun/filebrowser/releases/download/v0.0.4-test/linux-amd64-filebrowser.tar.gz
RUN tar -xf linux-amd64-filebrowser.tar.gz -C /usr/local/bin

USER root

# 创建数据存储目录
RUN mkdir -p /data /config

# 配置环境变量
ENV FB_PORT=9000
ENV FB_ADDRESS=0.0.0.0
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

EXPOSE ${FB_PORT}
# 设置入口点
ENTRYPOINT ["filebrowser"]